apiVersion: v1
kind: ConfigMap
metadata:
  name: article-platform-config
  namespace: article-platform
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "postgres_db"
  DB_USERNAME: "postgres"
  DB_SSL: "false"
  AWS_REGION: "us-east-1"
  S3_UPLOADS_BUCKET: "article-platform-uploads"
  AWS_ENDPOINT_URL: "http://localstack:4566"
  EMAIL_FROM: "DevOps Articles <noreply@example.me>"
  APP_URL: "http://localhost:3000"
