apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: article-platform-app
  namespace: article-platform
spec:
  selector:
    matchLabels:
      app: article-platform-app
  namespaceSelector:
    matchNames:
      - article-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
