apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: article-platform
spec:
  type: NodePort
  selector:
    app: article-platform-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080