services:
 jenkins:
  build:
   context: .
   dockerfile: Dockerfile
   args:
    DOCKER_GID: "1001"
  ports:
   - "8080:8080"
  volumes:
   - jenkins-volume:/var/jenkins_home
   - /var/run/docker.sock:/var/run/docker.sock
  restart:
   unless-stopped

volumes:
  jenkins-volume:
   driver: local
